blog/urls.py
from django.urls import path, re_path, include
from . import views

app_name='blog'

#urlpatterns = [
#	path('', views.index, name = "index"),
#	path('post/(<slugInput>[\w-]+)/', views.detailPost),
#	path('category/(<categoryInput>[\w-]+)/', views.categoryPost),
#]

urlpatterns = [
	re_path(r'^$', views.index, name = "index"),
	re_path(r'^post/(?P<slugInput>[\w-]+)/$', views.detailPost, name = "detailPost"),
	re_path(r'^category/(?P<categoryInput>[\w-]+)/$', views.categoryPost, name = "categoryPost"),
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views



urlpatterns = [
    path('', views.index, name="index"),
	path('blog/',include('blog.urls', namespace="blog")),
    path('admin/', admin.site.urls),
]

#urlpatterns = [
#    re_path(r'^$', views.index, name="index"),
#    re_path(r'^blog/',include('blog.urls')),
#    re_path (r'^admin/', admin.site.urls),
#]

blog/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.

class Post(models.Model):
	judul		= models.CharField(max_length=255)
	body		= models.TextField()
	category	= models.CharField(max_length=255)
	publish		= models.DateTimeField(auto_now_add = True)
	update		= models.DateTimeField(auto_now = True)
	slug		= models.SlugField(blank=True, editable = False)


	def save(self):
		self.slug = slugify(self.judul)
		super(Post, self).save()

	def __str__(self):
		return "{}. {}".format(self.id,self.judul)

blog/views.py
from django.shortcuts import render

# Create your views here.
from .models import Post

def index(request):
	posts = Post.objects.all();
	categories = Post.objects.values('category').distinct();
	contex = {
		'title':'Home Blog',
		'subTitle' : 'Blog',
		'content':'ini adalah halaman blog',
		'Categories':categories,
		'Posts':posts,
	}

	return render(request,'blog/index.html',contex)

def categoryPost(request,categoryInput):
	posts = Post.objects.filter(category=categoryInput);
	categories = Post.objects.values('category').distinct();
	contex = {
		'title':'Home Blog',
		'subTitle' : 'Blog',
		'content':'tampilkan berdasarkan category',
		'Categories':categories,
		'Posts':posts,
	}

	return render(request,'blog/category.html',contex)


def detailPost(request,slugInput):
	posts = Post.objects.get(slug=slugInput);
	categories = Post.objects.values('category').distinct();
	contex = {
		'title':'Home Blog',
		'subTitle' : 'Blog',
		'content':'ini adalah halaman blog',
		'Categories':categories,
		'Posts':posts,
	}

	return render(request,'blog/detail.html',contex)

mywebsite/views.py
from django.shortcuts import render


def index(request):
	context = {
		'title':'Home Page',
		'subTitle' : 'Selamat Datang',
		'content':'ini adalah home page dari website ini'
	}

	return render(request,'index.html',context)

blog/templates/blog/category.html
{% extends 'base.html' %}
{% load static %}

{% block Title %}
    {{title}}
{% endblock Title %}

{% block app_css %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock app_css %}

{% block header %}
<h1 class="display-4">{{title}}</h1>
<p class="lead">{{subTitle}}</p>
{% endblock header %}

{% block pageTitle %}
<div class="row" style="height: 100px;">
    <h1>{{title}} </h1>
</div>
{% endblock pageTitle %}

{% block contents %}
{{content}}
<ul class="nav">
    <li class="nav-item">
        <a class="nav-link" href='{% url 'blog:index' %}'>
            All-post
        </a>
    </li>

    {% for dataCategory in Categories  %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:categoryPost' categoryInput=dataCategory.category %}">
            {{dataCategory.category}}
        </a> 
    </li>
    {% endfor %}
</ul>

{% for post in Posts %}
<a href="/blog/post/{{post.slug}}">
    <h1>{{ post.judul }}</h1>
</a>
<p>{{ post.publish }}</p>
<p>{{ post.body|truncatechars:200 }}</p>
{% endfor %}

{% endblock contents %}

blog/templates/blog/detail.html
{% extends 'base.html' %}
{% load static %}

{% block Title %}
    {{title}}
{% endblock Title %}

{% block app_css %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock app_css %}

{% block header %}
<h1 class="display-4">{{title}}</h1>
<p class="lead">{{subTitle}}</p>
{% endblock header %}

{% block pageTitle %}
<div class="row" style="height: 100px;">
    <h1>{{title}} </h1>
</div>
{% endblock pageTitle %}

{% block contents %}
    {{content}}
    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href='{% url 'blog:index' %}'>
                All-post
            </a>
        </li>
    
        {% for dataCategory in Categories  %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:categoryPost' categoryInput=dataCategory.category %}">
                {{dataCategory.category}}
            </a> 
        </li>
        {% endfor %}
    </ul>
        <h1>{{ Posts.judul }}</h1>
        <p>{{ Posts.publish }}</p>
        <p>{{ Posts.body }}</p>

{% endblock contents %}
    
    

blog/templates/blog/index.html
{% extends 'base.html' %}
{% load static %}

{% block Title %}
    {{title}}
{% endblock Title %}

{% block app_css %}
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
{% endblock app_css %}

{% block header %}
<h1 class="display-4">{{title}}</h1>
<p class="lead">{{subTitle}}</p>
{% endblock header %}

{% block pageTitle %}
<div class="row" style="height: 100px;">
    <h1>{{title}} </h1>
</div>
{% endblock pageTitle %}

{% block contents %}
    {{content}}

    <ul class="nav">
        <li class="nav-item">
            <a class="nav-link" href='{% url 'blog:index' %}'>
                All-post
            </a>
        </li>
    
        {% for dataCategory in Categories  %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:categoryPost' categoryInput=dataCategory.category %}">
                {{dataCategory.category}}
            </a> 
        </li>
        {% endfor %}
    </ul>
    
    {% for post in Posts %}
        <a href="{% url 'blog:detailPost' slugInput=post.slug %}">
            <h1>{{ post.judul }}</h1>
        </a>
        <p>{{ post.publish }}</p>
        <p>{{ post.body|truncatechars:200 }}</p>
    {% endfor %}
        
{% endblock contents %}
    
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>

        {% block Title %}

        {% endblock Title %}

    </title>

    {% include 'snippets/style.html' %}
    
    {% block app_css %}
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% endblock app_css %}
        

</head>

<body>
    {% include 'snippets/navbar.html' %}

    <div class="jumbotron jumbotron-fluid">
        <div class="container text-white text-center">

            {% block header %}
                
            {% endblock header %}
                
        </div>
    </div>

    <div class="container-fluid">
        <div class="container bg-white text-dark shadow" style="margin-top:-100px;" id="myBody">
            {% block pageTitle %}

            {% endblock pageTitle %}
        </div>
    </div>
    
    <!--<div class="container" style="margin-top: 100px;">
        <h1>
            
        </h1>
    </div>-->

    <div class="container bg-light shadow mt-5">
        {% block contents %}

        {% endblock contents %}
    </div>

    {% include 'snippets/scripts.html' %}
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block Title %}
    {{title}}
{% endblock Title %}

{% block header %}
<h1 class="display-4">{{title}}</h1>
<p class="lead">{{subTitle}}</p>
{% endblock header %}

{% block pageTitle %}
<div class="row" style="height: 100px;">
    <h1>{{title}} </h1>
</div>
<div class="row" style="height: 70px;">
    <h3>{{content}} </h3>
</div>
{% endblock pageTitle %}

templates/snippets/navbar.html
{% load static %}

<nav class="navbar fixed-top navbar-expand-md navbar-dark" id="myNav">
    <div class="container">
        <a class="navbar-brand" href="/">
            <!--<<h1>Kelas Terbuka</h1>-->
            <img style="height: 50px;" src="{% static 'img/logo.png' %}" alt="">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a href="{% url 'index' %}" class="nav-link" style="color: white;">
                        Home
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'blog:index' %}" class="nav-link" style="color: white;">
                        Blog
                    </a>
                </li>

                <li class="nav-item">
                    <a href="{% url 'admin:index' %}" class="nav-link" style="color: white;">
                        Admin
                    </a>
                </li>
            </ul>
        </div>

    </div>
</nav>

templates/snippets/scripts.html
{% load static %}

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

<script src="{% static 'js/scrolling.js' %}"></script>

templates/snippets/style.html
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">